CREATE TABLE IF NOT EXISTS match (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  images VARCHAR(2000) NOT NULL,
  league VARCHAR(50) NOT NULL,
  home_team VARCHAR(50) NOT NULL,
  away_team VARCHAR(50) NOT NULL,
  home_score INT,
  away_score INT,
  status VARCHAR(20) NOT NULL,
  "minute" VARCHAR(10),
  match_time VARCHAR(30) NOT NULL,
  venue VARCHAR(100) NOT NULL,
  create_time INT NOT NULL,
  update_time INT NOT NULL,
  is_deleted TINYINT NOT NULL DEFAULT 0
);
