CREATE TABLE IF NOT EXISTS match (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  images VARCHAR(2000),
  league VARCHAR(50) NOT NULL,
  home_team VARCHAR(50) NOT NULL,
  away_team VARCHAR(50) NOT NULL,
  home_score INT,
  away_score INT,
  status VARCHAR(20) NOT NULL,
  "minute" VARCHAR(10),
  match_time VARCHAR(30) NOT NULL,
  venue VARCHAR(100),
  create_time INT NOT NULL,
  update_time INT NOT NULL,
  is_deleted TINYINT NOT NULL DEFAULT 0
);

INSERT INTO match (id, images, league, home_team, away_team, home_score, away_score, status, "minute", match_time, venue, create_time, update_time, is_deleted)
VALUES (1, 'https://picsum.photos/seed/match1a/800/450$https://picsum.photos/seed/match1b/800/450$https://picsum.photos/seed/match1c/800/450', 'PREMIER LEAGUE', 'Arsenal', 'Chelsea', 3, 1, 'FINISHED', NULL, 'Jul 5, 2026 20:00', 'Emirates Stadium', 1724000000, 1724000000, 0);

INSERT INTO match (id, images, league, home_team, away_team, home_score, away_score, status, "minute", match_time, venue, create_time, update_time, is_deleted)
VALUES (2, 'https://picsum.photos/seed/match2a/800/450$https://picsum.photos/seed/match2b/800/450', 'LA LIGA', 'Real Madrid', 'Barcelona', 2, 2, 'LIVE', '78', 'Aug 30, 2026 21:00', 'Santiago Bernabeu', 1724000000, 1724000000, 0);

INSERT INTO match (id, images, league, home_team, away_team, home_score, away_score, status, "minute", match_time, venue, create_time, update_time, is_deleted)
VALUES (3, 'https://picsum.photos/seed/match3a/800/450', 'BUNDESLIGA', 'Bayern Munich', 'Dortmund', NULL, NULL, 'SCHEDULED', NULL, 'Sep 10, 2026 18:30', 'Allianz Arena', 1724000000, 1724000000, 0);
